### ISSUE TITLE
minify uses old version of node, breaking the minification

### ISSUE THREAD

**Issue by megagustav** [anthonyftwang/minify-action#4]
```
npm WARN notsup Unsupported engine for minify@7.0.1: wanted: {"node":">=14"} (current: {"node":"12.21.0","npm":"6.14.11"})
5
npm WARN notsup Not compatible with your version of node/npm: minify@7.0.1
```

We even manually set our action to use the latest version of ubuntu (20.04, which comes with node 14). The script still loads version 12.xx

**Comment by anthonyftwang** [comment]
Specifying `uses: anthonyftwang/minify-action@v1.0.1` should resolve any version mismatches. Updated the example and will close for now; please re-open if issue persists.
